Ext.Loader.setPath('Ext.ux','/jscomponent/extjs/us/');
var store;
Ext.define('BeifengBPM.FlowRole',{
	extends:'Ext.ux.desktop.Module',
	requires:[
	],
	id:'flowrole',
	init:function(){
		this.launcher={
		text:'角色管理',
		iconCls:'notepad',
		handler:this.createWindow,
		scope:this
		}
	},
	createRoleGird:function(){
		Ext.define('RoleModel',{
			extend:'Ext.data.Model',
			fields:[
			        'flowroleId',
			        'flowrolename',
			        'flowrolemark'
			]
		});
		store=Ext.create('Ext.data.Store',{
			model:'RoleModel',
			pageSize:10,
			proxy:{
				type:'ajax',
				url:'/beifengbpm/queryRoleList.do',
				reader:{
					root:'roles',
					totalProperty:'totalCount'
				}
			}
		});
		var grid=Ext.create('Ext.grid.Panel',{
			store:store,
			border:false,
			columnLines:true,
			disableSelection:false,
			columns:[{
				id:'flowroleId',
				dataIndex:'flowroleId',
				hidden:true
			},{
				name:'flowrolename',
				dataIndex:'flowrolename',
				text:'角色名称'
			},{
				name:'flowroleremark',
				dataIndex:'flowroleremark',
				text:'角色描述'
			}],
			bbar:Ext.create('Ext.PagingToolbar',{
				store:userstore,
				displayInfo:true,
				displayMsg:'当前显示第 {0}条 至 {1}条记录 ，共 {2}条记录',
				emptyMsg:"暂无可用数据"
			}),
			tbar:[{
				width:240,
				fieldLabel:'搜索',
				xtype:'searchfield',
				labelWidth:50,
				store:store
			},{
				xtype:'button',
				width:80,
				text:'角色添加',
				handler:function(){
					var win;
					var form=Ext.create('Ext.form.Panel',{
						defaultType:'textfield',
						frame:true,
						items:[{
							id:'flowrolename',
							name:'flowrolename',
							fieldLabel:'角色名称',
							anchor:'100%',
							allowBlank:flase
						},{
							id:'flowroleremark',
							name:'flowroleremark',
							fieldLabel:'角色描述',
							anchor:'100%',
							xtype:'textarea'
						}],
						buttons:[{
							text:'重置',
							handler:function(){
							this.up('form').getForm().reset();
							}
						},{
							text:'提交',
							handler:function(){
								var f=this.up('form').getForm();
								var flowrolename=f.findField('flowrolename').getValue();
								var flowroleremark=f.findField('flowroleremark').getValue();
								Ext.Ajax.request({
									url:'/beifengbpm/addrole.do',
									method:'POST',
									params:{
										flowrolename:flowrolename,
										flowroleremark:flowroleremark
									},
									success:function(response,options){
										if(response.responseText=="addok"){
											Ext.Msg.alert('成功','添加角色成功');
											win.close();
											store.load();
										}else{
											Ext.Msg.alert('失败','添加角色失败');
										}
									},
									failure:function(response,options){
										Ext.Msg.alert('抱歉','服务器异常,请稍后添加');
									}
								});
							}
						}],
					});
					win=Ext.create('Ext.window.Window',{
						width:400,
						height:400,
						layout:'fit',
						items:[form]
					});
					win.show();
				}
			},{
				xtype:'button',
				width:80,
				text:'修改角色',
				handler:function(){
					var record = grid.getSelectionModel().getSelection();
					if(record.length==0){
						Ext.Msg.alert('警告','请至少选择一条需要修改的数据');
						return;
					}
					var flowroleId=record[0].get('flowroleId');
					var flowrolename=record[0].get('flowrolename');
					var flowroleremark=record[0].get('flowroleremartk').replace("<br>","\n");
					var form=Ext.create('Ext.form.Panel',{
						defaultType:'textfield',
						frame:true,
						items:[{
							id:'flowrolename',
							name:'flowrolename',
							fieldLabel:'角色名称',
							anchor:'100%',
							value:flowrolename,
							allowBlank:false
						},{
							id:'flowroleremark',
							name:'flowroleremark',
							fieldLabel:'角色描述',
							anchor:'100% 60%',
							value:flowroleremark,
							xtype:'textarea'
						}],
						buttons:[{
							text:'重置',
							handler:function(){
							this.up('form').getForm().reset();
							}
						},{
							text:'提交',
							handler:function(){
							var f=this.up('form').getForm();
							flowrolename=f.findField('flowrolename').getValue();
							flowroleremark=f.findField('flowroleremark').getValue();
							Ext.Ajax.request({
								url:'/beifengbpm/updaterole.do',
								method:'POST',
								params:{
									flowroleId:flowroleId,
									flowrolename:flowrolename,
									flowroleremark:flowroleremark
								},
								success:function(response,options){
									if(response.responseText=='updateok'){
										Ext.Msg.alert('成功','修改角色成功');
										win.cloese;
										store.load();
									}else{
										Ext.Msg.alert('失败','修改角色失败');
									}
								},
								failure:function(response,options){
									Ext.Msg.alert('抱歉','服务器异常，请稍后添加！');
								}
							});
							}
						}]
					});
					win=Ext.create('Ext.window.Window',{
						width:400,
						height:400,
						title:'修改角色',
						layout:'fit',
						items:[form]
					});
					win.show();
				}
			},{
				xtype:'button',
	        	width:80,
	        	text:'删除角色',
	        	handler:function(){
					var record=grid.getSelectionModel().getSelection();
					if(record.length==0){
	        			Ext.Msg.alert('警告','请至少选择一条需要删除的数据！');
	        			return;
	        		}
					Ext.Msg.confirm('确认','是否确认删除该角色?',function(bt){
						if(bt=='yes'){
							var flowroleId=record[0].get('flowroleId');
							Ext.Ajax.request({
								url:'/beifengbpm/deleteRole.do',
								method:'POST',
								params:{
								flowroleId:flowroleId
								},
								success:function(response,options){
									if(response.responseText=='deleteok'){
										Ext.Msg.alert('成功','删除角色成功');
										store.load();
									}else{
										Ext.Msg.alert('失败','删除角色失败');
									}
								},
								failure:function(response,options){
									Ext.Msg.alert('抱歉','服务器异常,请稍后操作');
								}
							});
						}
					});
				}
			},{
				xtype:'button',
				text:'分配用户',
				width:80,
				handler:function(){
					var win;
					var record=grid.getSelectionModel().getSelection();
					if(record.length==0){
						Ext.Msg.alert('警告','请至少选择一个需要分配用户的角色');
						return;
					}
					var flowroleId=record[0].get('flowroleId');
					store=Ext.create('Ext.data.TreeStore',{
						proxy:{
							type:'ajax',
							url:'/beifengbpm/queryDepartandUser.do',
						},
						sorters:[{
							property:'leaf',
							direction:'ASC'
						},{
							property:'text',
							direction:'ASC'
						}]
					});
					var tree=Ext.create('Ext.tree.Panel',{
						store:store,
						rootVisible:false,
						useArrows:true,
						frame:true,
						dockedItems:[{
							xtype:'toolbar',
							items:{
								text:'分配用户',
								handler:function(){
									var records=tree.getView().getChecked();
									var ids="";
									for(var i=0;i<records.length;i++){
										ids+="'"+records[i].get('id')+"'";
										if(i<records.length-1){
											ids+=","
										}
									}
									Ext.Ajax.request({
										url:'/beifengbpm/updateuserRole.do',
										method:'POST',
										params:{
											ids:ids,
											flowroleId:flowroleId
										},
										success:function(response,options){
											if(response.responseText=='updateok'){
												Ext.Msg.alert('成功','分配用户成功');
												win.close();
											}else{
												Ext.Msg.alert('失败','分配用户失败');
											}
										},
										failure:function(respnse,options){
											Ext.Msg.alert('抱歉','服务器错误,请稍后再试');
										}
									});
								}
							}
						}]
					})
					win=Ext.create('Ext.window.Window',{
						width:400,
						height:500,
						title:'选择用户',
						layout:'fit',
						items:[tree]
					});
					win.show();
				}
			}]
		});
		store.loadPage(1);
		return grid;
	},
	createWindow:function(){
		var desktop=this.app.getDesktop();
		var win= desktop.getWindow('flowrole');
		if(!win){
			win=desktop.createWindow({
				id:'flowrole',
				title:'角色管理',
				width:600,
				height:400,
				iconCls:'notepad',
				animCollapse:false,
				border:false,
				hideMode:'offsets',
				layout:'fit',
				items:[this.createRoleGrid()]
			});
		}
		win.show();
		return win;
	}
});
